Github will render jupyter notebooks, but Bokeh plots won't work<br>
View this notebook with NBViewer:<br>
https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/main.ipynb

# Welcome to my hydrology modeling tool, Hydro
<br>
## This model is a continuation of my work:
<br>
Patton, Douglas A, Rebecca Moore, Alan P Covich, and John C Bergstrom. 2013. “Ex-Post Reliability
Assessment of Benefit Transfer Valuation Estimates of Wetland Ecosystem Service Supported by
Okefenokee National Wildlife Refuge.” SSRN Working Paper. https://ssrn.com/abstract=2294080

In [1]:
import numpy as np
import USGShydro #view via https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/helpers.ipynb

Loading BokehJS ...

to do:
### tools for handling data
-USGShydro.py<br>
<https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/helpers.ipynb><br>
- ~~download rainfall~~ 
- ~~download runoff~~
- ~~research time conversions~~
- ~~match data values aross time values~~
- ~~check for gaps in time~~
- ~~convert data to numpy array~~
- ~~create simple plot to view downloaded gage and precip data~~
- verify parameter download
- handle errors
- merge time series from different XML files capability
    - check data from overlapping time periods
    - accomodate series with unequal frequencies
        - distinguish between missing values and lower frequency series
- Use bokeh to interactively plot each site, its basin, and NLCD data.
    - overlay rainfall runoff?
    - multi site tool to connect rainfall runoff plot to each basin?

-----------------------
### tools for modeling runoff
rainfallrunoff.py
- create time series dataset of lags, etc.
- drop observations with missing values
- create and run
    - simple distributed lag model
    - Locally weighted distributed lag model
        - point estimate
        - weighted average
- plot predicted runoff vs. actual
- predict days above flood stage with models trained over different time periods

-----------------------
### general time series tools
tstools.py
- ~~create tool to create lagged variables~~

-----------------------
### Multi-site tools
- Missing data
    - combine with nearby site data and use latent variable matrix factorization based approach to fill in missing values
- create tool to query sites for availability of needed series
- compare sites and see if model relates to hydrologic featues, basin topography, landcover, etc.
------------------------


#### setup the request

In [2]:
site='02314500' #Fargo, Ga below the Okefenokee NWR
start='2011-01-01T00:00-0400'
start='2010-12-01T00:00-0400'
end='2011-03-15T00:00-0400'
paramlist=['00045', '00065'] #must be entered as strings


#### setup a single, global (for this site and data) distributed lag model for all of the data with all 0 to 30 lags of precipitation, a single lag of runoff, a constant term

In [3]:
modelfeatures={'RRmodeltype':'distributed_lag', 'maxlag':90, 'startlag':0, 'incl_AR1':'yes','incl_constant':'yes','local':'no', 'local_count':0}#dictionary of model features

#### Create the object, downloading data if not already saved, saving if not already saved, clean data, convert to numpy and run the model with selected features. 

In [4]:
try1=USGShydro.Hydrositedatamodel(site,start,end,paramlist,modelfeatures) 

all series have matching times from start to end
all time steps are evenly spaced
The request has returned 9981 observations for 2 series


### The plot below is created with the Python package, 'bokeh'. You can manipulate the plot using the tools on the right side. 

In [5]:
try1.simpleplot() #plot a time series of rainfall and gage height (above minimum for series)

#### print numpy array of m observations spaced evenly from start to end time (time,precip,gageht)

In [6]:
m=10
try1.data_array[0:try1.data_array.shape[0]:int(try1.data_array.shape[0]/m),:]

array([[0.00000000e+00, 2.00000000e-02, 5.30000000e-01],
       [1.03958333e+01, 0.00000000e+00, 4.40000000e-01],
       [2.07916667e+01, 0.00000000e+00, 6.20000000e-01],
       [3.11875000e+01, 0.00000000e+00, 7.10000000e-01],
       [4.15833333e+01, 0.00000000e+00, 9.50000000e-01],
       [5.19791667e+01, 0.00000000e+00, 9.80000000e-01],
       [6.23750000e+01, 0.00000000e+00, 1.10000000e+00],
       [7.27708333e+01, 0.00000000e+00, 1.67000000e+00],
       [8.31666667e+01, 0.00000000e+00, 1.33000000e+00],
       [9.35625000e+01, 0.00000000e+00, 1.12000000e+00],
       [1.03958333e+02, 0.00000000e+00, 1.22000000e+00]])

### run the first model as specified by the model features dictionary above

In [7]:
try1.runTSmodel1()

betas: [0.45811865 0.00970362 0.02057495 0.02478774 0.02905735 0.03217559
 0.03504956 0.03722524 0.03898221 0.04051325 0.04222069 0.04405131
 0.04574156 0.04792646 0.04880539 0.05069378 0.05061536 0.05115102
 0.05061059 0.05096897 0.05111409 0.0510338  0.05157255 0.05244293
 0.05321065 0.05334991 0.05354166 0.05368108 0.0546785  0.05533978
 0.05572185 0.05679724 0.05770006 0.05839131 0.05885544 0.05933175
 0.05947847 0.05977833 0.06055987 0.06090142 0.06068031 0.06064155
 0.06019878 0.06062903 0.06032483 0.0608974  0.06216616 0.06305475
 0.06339773 0.06391609 0.06473297 0.06504128 0.06535618 0.06663324
 0.06742766 0.06816513 0.06899289 0.06917854 0.07012589 0.07102145
 0.07207035 0.07252933 0.07310539 0.07300073 0.07510994 0.07574669
 0.07735926 0.07867311 0.07755729 0.07829965 0.08130463 0.08212964
 0.08393581 0.08541092 0.08652372 0.08742587 0.09014723 0.09244332
 0.09429565 0.09716189 0.10104876 0.10579745 0.10991063 0.11312094
 0.11845627 0.12258749 0.12770091 0.1320465  0.13920919

#### verify the lag structure of the data

In [8]:
print(try1.model.lagprecip[-10:,0:14])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### try again with new model features

In [9]:
try1.runTSmodel1({'RRmodeltype':'distributed_lag', 'maxlag':300, 'startlag':100, 'incl_AR1':'yes','incl_constant':'yes','local':'no', 'local_count':0})

betas: [0.43522338 0.00970212 0.34719982 0.2704965  0.23477051 0.19301881
 0.17645772 0.16290078 0.15560351 0.14613267 0.1408238  0.1330205
 0.12945567 0.12468401 0.11870437 0.11861879 0.11737567 0.11771015
 0.11677803 0.11886616 0.12023721 0.11978261 0.11975389 0.12038471
 0.12154203 0.12412857 0.12324506 0.12596833 0.12424902 0.12388827
 0.12199412 0.12193911 0.12240358 0.12161593 0.12087782 0.1201951
 0.12267    0.12130548 0.12164533 0.12225705 0.12250788 0.1231392
 0.12443299 0.12267258 0.12410607 0.12461011 0.12600193 0.12655807
 0.12653277 0.12793595 0.12688805 0.12582294 0.12380328 0.12412133
 0.12395749 0.12412447 0.12334245 0.12135822 0.12451641 0.12287354
 0.12185436 0.12137181 0.12145749 0.11852293 0.11728197 0.11930777
 0.12057173 0.11972018 0.12184566 0.11875806 0.12092835 0.12046017
 0.11972263 0.11922394 0.11862015 0.11763096 0.11705134 0.11703304
 0.11554334 0.11542737 0.11454213 0.11257153 0.11197061 0.11119255
 0.11126689 0.11118883 0.11087019 0.11074054 0.11014753 0.

#### Create and check pandas dataset for each observation to prepare for geopandas

In [10]:
try1.geoplot() #create pandas dataset for each series to prepare for gis plotting
try1.df.head()

longitude     latitude        CRS                               site_name
0  -82.5605556  30.68055556  EPSG:4326  SUWANNEE RIVER AT US 441, AT FARGO, GA
1  -82.5605556  30.68055556  EPSG:4326  SUWANNEE RIVER AT US 441, AT FARGO, GA