Github will render jupyter notebooks, but Bokeh plots won't work<br>
View this notebook with NBViewer:<br>
https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/main.ipynb

# Welcome to my hydrology modeling tool, Hydro
<br>
## This model is a continuation of my work:
<br>
Patton, Douglas A, Rebecca Moore, Alan P Covich, and John C Bergstrom. 2013. “Ex-Post Reliability
Assessment of Benefit Transfer Valuation Estimates of Wetland Ecosystem Service Supported by
Okefenokee National Wildlife Refuge.” SSRN Working Paper. https://ssrn.com/abstract=2294080

In [1]:
import numpy as np
import USGShydro #view via https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/helpers.ipynb

Loading BokehJS ...

to do:
### tools for handling data
-USGShydro.py<br>
<https://nbviewer.jupyter.org/github/DouglasPatton/Hydro/blob/master/helpers.ipynb><br>
- ~~download rainfall~~ 
- ~~download runoff~~
- ~~research time conversions~~
- ~~match data values aross time values~~
- ~~check for gaps in time~~
- ~~convert data to numpy array~~
- ~~create simple plot to view downloaded gage and precip data~~
- verify parameter download
- handle errors
- merge time series from different XML files capability
    - check data from overlapping time periods
    - accomodate series with unequal frequencies
        - distinguish between missing values and lower frequency series
- Use bokeh to interactively plot each site, its basin, and NLCD data.
    - overlay rainfall runoff?
    - multi site tool to connect rainfall runoff plot to each basin?

-----------------------
### tools for modeling runoff
RainfallRunoff.py
- create time series dataset of lags, etc.
- drop observations with missing values
- create and run
    - simple distributed lag model
    - Locally weighted distributed lag model
        - point estimate
        - weighted average
- plot predicted runoff vs. actual
- predict days above flood stage with models trained over different time periods

-----------------------
### Multi-site tools
- Missing data
    - combine with nearby site data and use latent variable matrix factorization based approach to fill in missing values
- create tool to query sites for availability of needed series
- compare sites and see if model relates to hydrologic featues, basin topography, landcover, etc.

### setup the request

In [2]:
site='02314500' #Fargo, Ga below the Okefenokee NWR
start='2011-01-01T00:00-0400'
end='2011-03-01T00:00-0400'
paramlist=['00045', '00065'] #must be entered as strings
modelfeatures={'RRmodeltype':'distributed_lag', 'maxlag':30, 'startlag':0, 'AR1':'yes','local':'no', 'local_count':0}#dictionary of model features

In [3]:
try1=USGShydro.Hydrositedatamodel(site,start,end,paramlist,modelfeatures) #create the object, retri

all series have matching times from start to end
all time steps are evenly spaced
The request has returned 5681 observations for 2 series
*** (5651, 1) (5651, 31)
(5651, 32)


### The plot below is created with the Python package, 'bokeh'. You can manipulate the plot using the tools on the right side. 

In [4]:
try1.simpleplot() #plot a time series of rainfall and gage height (above minimum for series)

In [5]:
#print numpy array of 20 observations spaced evenly from start to end time [time,precip,gageht]
try1.data_array[0:try1.data_array.shape[0]:int(try1.data_array.shape[0]/20),:]

array([[ 0.        ,  0.        ,  0.7       ],
       [ 2.95833333,  0.        ,  0.92      ],
       [ 5.91666667,  0.        ,  0.93      ],
       [ 8.875     ,  0.        ,  0.9       ],
       [11.83333333,  0.        ,  0.94      ],
       [14.79166667,  0.        ,  0.91      ],
       [17.75      ,  0.        ,  0.99      ],
       [20.70833333,  0.        ,  0.97      ],
       [23.66666667,  0.        ,  0.92      ],
       [26.625     ,  0.        ,  1.18      ],
       [29.58333333,  0.        ,  1.12      ],
       [32.54166667,  0.        ,  1.13      ],
       [35.5       ,  0.        ,  1.14      ],
       [38.45833333,  0.        ,  1.33      ],
       [41.41666667,  0.        ,  1.66      ],
       [44.375     ,  0.        ,  1.6       ],
       [47.33333333,  0.        ,  1.51      ],
       [50.29166667,  0.        ,  1.41      ],
       [53.25      ,  0.        ,  1.31      ],
       [56.20833333,  0.        ,  1.24      ],
       [59.16666667,  0.        ,  1.2  

In [6]:
try1.geoplot()
try1.df

longitude     latitude        CRS                               site_name
0  -82.5605556  30.68055556  EPSG:4326  SUWANNEE RIVER AT US 441, AT FARGO, GA
1  -82.5605556  30.68055556  EPSG:4326  SUWANNEE RIVER AT US 441, AT FARGO, GA

In [7]:
print(try1.model.lagprecip[85:93,0:8])
print(try1.model.data.shape)

[[0.02 0.02 0.03 0.02 0.01 0.01 0.   0.  ]
 [0.03 0.02 0.02 0.03 0.02 0.01 0.01 0.  ]
 [0.03 0.03 0.02 0.02 0.03 0.02 0.01 0.01]
 [0.03 0.03 0.03 0.02 0.02 0.03 0.02 0.01]
 [0.02 0.03 0.03 0.03 0.02 0.02 0.03 0.02]
 [0.03 0.02 0.03 0.03 0.03 0.02 0.02 0.03]
 [0.02 0.03 0.02 0.03 0.03 0.03 0.02 0.02]
 [0.02 0.02 0.03 0.02 0.03 0.03 0.03 0.02]]
(5681, 3)
